apiVersion: v1
kind: Service
metadata:
  name: tenant-clusterip-service
  labels:
    app: tenant
  annotations:
spec:
  type: ClusterIP
  selector:
    app: tenant
  ports:
    - port: 80
      targetPort: 80

   