apiVersion: apps/v1
kind: Deployment
metadata:
  name: vendor-deployment
  labels:
    app: vendor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vendor
  template:
    metadata:
      labels:
        app: vendor
    spec:
      containers:
        - name: vendor
          image: acraendevfab.azurecr.io/vendor
          ports:
            - containerPort: 80

   