apiVersion: v1
kind: Service
metadata:
  name: avendor-clusterip-service
  labels:
    app: vendor
  annotations:
spec:
  type: ClusterIP
  selector:
    app: vendor
  ports:
    - port: 80
      targetPort: 80

   