apiVersion: v1
kind: Service
metadata:
  name: auth-clusterip-service
  labels:
    app: auth
  annotations:
spec:
  type: ClusterIP
  selector:
    app: auth
  ports:
    - port: 80
      targetPort: 80

   