apiVersion: v1
kind: Service
metadata:
  name: app4-nginx-clusterip-service
  labels:
    app: app4-nginx
  annotations:
spec:
  type: ClusterIP
  selector:
    app: app4-nginx
  ports:
    - port: 80
      targetPort: 3000

   